abstract: TT Filter using HTML::Scrubber
author: 'Yu Isobe <yupug@cpan.org>'
build_requires:
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Template-Plugin-Filter-HTMLScrubber
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  HTML::Scrubber: 0
  Template: 0
  Template::Plugin::Filter: 0
version: 0.01
